name: Bot Build and Deploy Production

on:
  push:
    branches: [master]
    paths:
      - "discord-bot/**"
      - ".github/workflows/bot-prod.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Build specific env vars
      CONFIG_ID: prod
      CONFIG_EXPLORER_ENDPOINT: ${{ secrets.PROD_CONFIG_EXPLORER_ENDPOINT }}
      CONFIG_DISCORD_TOKEN: ${{ secrets.PROD_CONFIG_DISCORD_TOKEN }}
      CONFIG_COIN_MARKET_CAP_KEY: ${{ secrets.PROD_COIN_MARKET_CAP_KEY }}
      GCP_SERVICE_ID: ${{ secrets.GCP_BOT_PROD_SERVICE_ID }}
      GCP_PROD_SERVICE_ID: ${{ secrets.GCP_PROD_SERVICE_ID }}
      GCP_PROD_DOMAIN: ${{ secrets.GCP_PROD_DOMAIN }}
      GCP_STAGING_SERVICE_ID: ${{ secrets.GCP_STAGING_SERVICE_ID }}
      GCP_STAGING_DOMAIN: ${{ secrets.GCP_STAGING_DOMAIN }}
      GCP_BOT_PROD_SERVICE_ID: ${{ secrets.GCP_BOT_PROD_SERVICE_ID }}
      GCP_BOT_PROD_DOMAIN: ${{ secrets.GCP_BOT_PROD_DOMAIN }}

    steps:
      - uses: actions/checkout@v2
      - name: Bot Config
        run: |
          cd discord-bot/src/data/
          mv config.template config.$CONFIG_ID.json
          sed -i 's/EXPLORER-ENDPOINT/${{ env.CONFIG_EXPLORER_ENDPOINT }}/g' config.$CONFIG_ID.json
          sed -i 's/DISCORD-TOKEN/${{ env.CONFIG_DISCORD_TOKEN }}/g' config.$CONFIG_ID.json
          sed -i 's/COIN-MARKET-CAP-KEY/${{ env.CONFIG_COIN_MARKET_CAP_KEY }}/g' config.$CONFIG_ID.json
      - name: GCP Config
        run: |
          cd discord-bot
          mv app.template.prod.yaml app.yaml
          sed -i 's/%SERVICE-ID%/${{ env.GCP_SERVICE_ID }}/g' app.yaml
          sed -i 's/%CONFIG-ID%/${{ env.CONFIG_ID }}/g' app.yaml
          mv dispatch.template.prod.yaml dispatch.yaml
          sed -i 's/%GCP-PROD-DOMAIN%/${{ env.GCP_PROD_DOMAIN }}/g' dispatch.yaml
          sed -i 's/%GCP-PROD-SERVICE-ID%/${{ env.GCP_PROD_SERVICE_ID }}/g' dispatch.yaml
          sed -i 's/%GCP-STAGING-DOMAIN%/${{ env.GCP_STAGING_DOMAIN }}/g' dispatch.yaml
          sed -i 's/%GCP-STAGING-SERVICE-ID%/${{ env.GCP_STAGING_SERVICE_ID }}/g' dispatch.yaml
          sed -i 's/%GCP-BOT-PROD-DOMAIN%/${{ env.GCP_BOT_PROD_DOMAIN }}/g' dispatch.yaml
          sed -i 's/%GCP-BOT-PROD-SERVICE-ID%/${{ env.GCP_BOT_PROD_SERVICE_ID }}/g' dispatch.yaml
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          version: latest
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy
        run: |
          cd discord-bot
          npm install
          npm run build
          gcloud app deploy app.yaml dispatch.yaml --quiet
