name: Build All with Node versions 12, 14

on:
  push:
    branches: [master, develop]
    paths:
      - "api/**"
      - "client/**"
      - ".github/workflows/build.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        run: |
          cd client
          npm install
          npm run build
          cd ../api
          npm install
          npm run build
